Insert Into estado (uf,estado) Values('AC','Acre');  
 Insert Into estado (uf,estado) Values('AL','Alagoas');  
 Insert Into estado (uf,estado) Values('AM','Amazonas');
 Insert Into estado (uf,estado) Values('AP','Amapá');
 Insert Into estado (uf,estado) Values('BA','Bahia');
 Insert Into estado (uf,estado) Values('CE','Ceará');
 Insert Into estado (uf,estado) Values('DF','Distrito Federal');
 Insert Into estado (uf,estado) Values('ES','Espírito Santo');
 Insert Into estado (uf,estado) Values('GO','Goiás');
 Insert Into estado (uf,estado) Values('MA','Maranhão');
 Insert Into estado (uf,estado) Values('MG','Minas Gerais');
 Insert Into estado (uf,estado) Values('MS','Mato Grosso do Sul');
 Insert Into estado (uf,estado) Values('MT','Mato Grosso');
 Insert Into estado (uf,estado) Values('PA','Pará');
 Insert Into estado (uf,estado) Values('PB','Paraíba');
 Insert Into estado (uf,estado) Values('PE','Pernambuco');
 Insert Into estado (uf,estado) Values('PI','Piauí');
 Insert Into estado (uf,estado) Values('PR','Paraná');
 Insert Into estado (uf,estado) Values('RJ','Rio de Janeiro');
 Insert Into estado (uf,estado) Values('RN','Rio Grande do Norte');
 Insert Into estado (uf,estado) Values('RO','Rondônia');
 Insert Into estado (uf,estado) Values('RR','Roraima');
 Insert Into estado (uf,estado) Values('RS','Rio Grande do Sul');
 Insert Into estado (uf,estado) Values('SC','Santa Catarina');
 Insert Into estado (uf,estado) Values('SE','Sergipe');
 Insert Into estado (uf,estado) Values('SP','São Paulo');
 Insert Into estado (uf,estado) Values('TO','Tocantins');