-- MySQL Script generated by MySQL Workbench
-- Tue Feb 11 09:14:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbClientes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbClientes` ;

-- -----------------------------------------------------
-- Schema dbClientes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbClientes` DEFAULT CHARACTER SET utf8 ;
USE `dbClientes` ;

-- -----------------------------------------------------
-- Table `dbClientes`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbClientes`.`Estado` ;

CREATE TABLE IF NOT EXISTS `dbClientes`.`Estado` (
  `cod_estado` INT NOT NULL AUTO_INCREMENT,
  `UF` CHAR(2) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbClientes`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbClientes`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `dbClientes`.`Cidade` (
  `cod_cidade` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(45) NOT NULL,
  `cod_estado` INT NOT NULL,
  PRIMARY KEY (`cod_cidade`),
  CONSTRAINT `fk_estado`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `dbClientes`.`Estado` (`cod_estado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbClientes`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbClientes`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `dbClientes`.`Endereco` (
  `cep` CHAR(9) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cod_cidade` INT NOT NULL,
  PRIMARY KEY (`cep`),
  CONSTRAINT `fk_cidade`
    FOREIGN KEY (`cod_cidade`)
    REFERENCES `dbClientes`.`Cidade` (`cod_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbClientes`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbClientes`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `dbClientes`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(8) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `rg` VARCHAR(15) NOT NULL,
  `guarda_religiosa` TINYINT NOT NULL,
  `obs` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_cep`
    FOREIGN KEY (`cep`)
    REFERENCES `dbClientes`.`Endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
